import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

plugins {
    id "com.vanniktech.maven.publish" version "0.35.0"
}

apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply plugin: 'signing'

android {
    namespace = 'com.longdo.mjpegviewer'
    compileSdkVersion = 36

    defaultConfig {
        aarMetadata {
            minCompileSdk = 14
        }
        minSdkVersion 21
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates("com.perthcpe23.dev", "android-mjpeg-view", "1.1.4")

    pom {
        name = "Android Mjpeg View"
        description = "Android custom View to render Mjpeg stream"
        url = "https://github.com/perthcpe23/android-mjpeg-view"
        licenses {
            license {
                name = "The MIT License (MIT)"
                url = "https://opensource.org/license/mit/"
            }
        }
        developers {
            developer {
                id = "perthcpe23"
                name = "Punyapat S"
                email = "perth.s28@gmail.com"
            }
        }
        scm {
            connection = "scm:git:git://github.com/perthcpe23/android-mjpeg-view.git"
            developerConnection = "scm:git:ssh://github.com:perthcpe23/android-mjpeg-view.git"
            url = "http://github.com/perthcpe23/android-mjpeg-view/tree/master"
        }
    }

    configure(new AndroidSingleVariantLibrary(
        "release",
        true,  // keep sources
        false  // Javadoc/Dokka
    ))
}

signing {
    sign publishing.publications
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
